<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.13.1 on win32)" generated="2025-03-04T22:17:27.304017" rpa="false" schemaversion="5">
<suite id="s1" name="Tests" source="C:\Users\Lenovo\Downloads\Winda\test\flight_automation\tests">
<suite id="s1-s1" name="Login Test" source="C:\Users\Lenovo\Downloads\Winda\test\flight_automation\tests\login_test.robot">
<test id="s1-s1-t1" name="User Can Login Successfully" line="7">
<kw name="Open Application" owner="AppiumLibrary" type="SETUP">
<msg time="2025-03-04T22:17:29.741846" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B47C3574D0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2025-03-04T22:17:31.785860" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B47C3B2490&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2025-03-04T22:17:33.833495" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B47C3B2710&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2025-03-04T22:17:35.876590" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2025-03-04T22:17:35.876097" elapsed="0.020096">No application is open</status>
</kw>
<msg time="2025-03-04T22:17:35.898200" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2025-03-04T22:17:35.899548" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B47C3C5CD0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<arg>http://127.0.0.1:4723/wd/hub</arg>
<arg>platformName=Android</arg>
<arg>deviceName=emulator-5554</arg>
<arg>automationName=UiAutomator2</arg>
<arg>appPackage=com.example.app</arg>
<arg>appActivity=.MainActivity</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://appium.io/docs/en/2.1/cli/args/
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2025-03-04T22:17:27.634618" elapsed="8.275705">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B47C3C5CD0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</kw>
<kw name="Close Application" owner="AppiumLibrary" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2025-03-04T22:17:35.912066" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2025-03-04T22:17:35.911757" elapsed="0.004089">No application is open</status>
</kw>
<msg time="2025-03-04T22:17:35.917775" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2025-03-04T22:17:35.919238" level="FAIL">No application is open</msg>
<doc>Closes the current application and also close webdriver session.</doc>
<status status="FAIL" start="2025-03-04T22:17:35.911289" elapsed="0.009602">No application is open</status>
</kw>
<doc>Menguji login dengan kredensial valid</doc>
<status status="FAIL" start="2025-03-04T22:17:27.633506" elapsed="8.287865">Setup failed:
MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B47C3C5CD0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Also teardown failed:
No application is open</status>
</test>
<status status="FAIL" start="2025-03-04T22:17:27.360299" elapsed="8.564377"/>
</suite>
<status status="FAIL" start="2025-03-04T22:17:27.305680" elapsed="8.621907"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Tests" id="s1" pass="0" fail="1" skip="0">Tests</stat>
<stat name="Login Test" id="s1-s1" pass="0" fail="1" skip="0">Tests.Login Test</stat>
</suite>
</statistics>
<errors>
<msg time="2025-03-04T22:17:29.741846" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B47C3574D0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2025-03-04T22:17:31.785860" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B47C3B2490&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2025-03-04T22:17:33.833495" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B47C3B2710&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2025-03-04T22:17:35.898200" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2025-03-04T22:17:35.917775" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
